#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6G -XX:+UseParallelGC

#Gradle
org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1G
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.daemon=true

# Kotlin Native Memory (iOS Compilation)
kotlin.native.disableCompilerDaemon=false

#Android
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# Use JDK 21 to avoid "error 25" (Kotlin DSL mismatch with JDK 25)

# Fix IrLinkageError on iOS

ksp.useKSP2=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false

android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.builtInKotlin=false
android.newDsl=false
